
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: addenda-pv-claim
  namespace: addenda
  labels:
    app: mongopv
spec:  
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
